import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { QueryClientProvider } from "@tanstack/react-query";
import queryClient from "../app/queryClient"; // حسب المسار اللي عملت فيه

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>{" "}
      </body>
    </html>
  );
}
