import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import AppProvider from "@/Providers/Provider";
import "./globals.css";

const main = Geist({
  variable: "--font-main-ui",
  subsets: ["latin"],
  weight: ["600", "700", "800", "900"],
});

const open = Geist_Mono({
  variable: "--font-open-ui",
  subsets: ["latin"],
  weight: ["500"],
});

export const metadata: Metadata = {
  title: "TechFlipp Frontend Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${open.variable} ${main.variable} antialiased`}>
        <AppProvider>
          <main className="w-full">{children}</main>
          <Toaster />
        </AppProvider>
      </body>
    </html>
  );
}
